/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Conexion.SQL;
import javax.swing.JOptionPane;

/**
 *
 * @author Javier
 */
public class AgregarProducto extends javax.swing.JPanel {
    
    private String ID = "";
    
    public AgregarProducto(String ID) {
        initComponents();
        this.ID = ID;
        init();
    }
    
    final void init(){
        bCodigo.setText(ID);
    }
    
    public static boolean isNumeric(String str)  
    {  
      try{
            double d = Double.parseDouble(str);  
      }catch(NumberFormatException nfe){  
        return false;  
      }  
      return true;  
    }
    
    void Limpiar(){
        bCodigo.setText("");
        bArticulo.setText("");
        bCantidad.setText("");
        bPrecio.setText("");
        bDescuento.setText("");
        bIVA.setText("");
    }
    
    boolean NoVacio(){
        if(!bCodigo.getText().equals("") && !bArticulo.getText().equals("") && !bCantidad.getText().equals("") && !bPrecio.getText().equals("") && !bDescuento.getText().equals("") && !bIVA.getText().equals("")){
            if(!bCodigo.getText().equals(" ") && !bArticulo.getText().equals(" ") && !bCantidad.getText().equals(" ") && !bPrecio.getText().equals(" ") && !bDescuento.getText().equals(" ") && !bIVA.getText().equals(" ")){
                if(isNumeric(bPrecio.getText()) && isNumeric(bDescuento.getText()) && isNumeric(bIVA.getText())){
                    return true;
                }else{
                    JOptionPane.showMessageDialog(null, "Asegurese de que el Precio, Descuento y IVA sean Valores Numericos");
                    return false;
                }
            }else{
                return false;
            }
        }else{
            return false;
        }
    }
    
    void Insert(){
        if(NoVacio()){
            String[] rows = {"Clave", "Articulo", "Cantidad", "Precio", "Descuento", "IVA"};
            String[] values = {bCodigo.getText(), bArticulo.getText(), bCantidad.getText(), bPrecio.getText(), bDescuento.getText(), bIVA.getText()};
            SQL.Insert("productos", rows, values);
            Limpiar();
            JOptionPane.showMessageDialog(null, "Producto Agregado Exitosamente");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        bArticulo = new javax.swing.JTextField();
        bCantidad = new javax.swing.JTextField();
        bPrecio = new javax.swing.JTextField();
        bIVA = new javax.swing.JTextField();
        bCodigo = new javax.swing.JTextField();
        bDescuento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("IVA");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 80, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Codigo");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 80, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Articulo");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 80, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Cantidad");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 80, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Precio");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 80, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Descuento");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 80, 20));
        add(bArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 340, -1));
        add(bCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 340, -1));
        add(bPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 340, -1));
        add(bIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 340, -1));
        add(bCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 340, -1));
        add(bDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 340, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Nuevo Producto");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 10, 420, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Insert();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bArticulo;
    private javax.swing.JTextField bCantidad;
    private javax.swing.JTextField bCodigo;
    private javax.swing.JTextField bDescuento;
    private javax.swing.JTextField bIVA;
    private javax.swing.JTextField bPrecio;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
