/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Conexion.Productos;
import Conexion.SQL;
import Conexion.XMLParser;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Javier
 */
public class Registros extends javax.swing.JPanel {

    /**
     * Creates new form Registros
     */
    public Registros() {
        initComponents();
        init();
    }
    
    void init(){
        setTabla("", "", "");
    }

    void setTabla(String sql, String where, String FSentence){
        String a[] = {"ID", "Cliente","Total"};
        if(sql.equals("") && where.equals("") && FSentence.equals("")){
            sql = "SELECT *";
            where = "FROM registroventas";
            FSentence = "ORDER BY ID";
        }
        DefaultTableModel t = SQL.getTables(sql, where, FSentence, a.length, a);
        TablaRegistros.getTableHeader().setReorderingAllowed(false);
        TablaRegistros.setModel(t);
    }
    
    void LlenarFrame(){
        JFrame frame = new JFrame();
        frame.setResizable(true);
        frame.setSize(new Dimension(484, 366));
        
        int a = Integer.parseInt(String.valueOf(TablaRegistros.getValueAt(TablaRegistros.getSelectedRow(), 0)));
        XMLParser w = new XMLParser(String.valueOf(a));
        ArrayList<Productos> prod = w.Parse();
        String columnas[] = {"Cliente", "Total"};
        String datos[] = SQL.llenar(String.valueOf(a), columnas, columnas.length, "registroventas", "ID");
        textID.setText(String.valueOf(a));
        textCliente.setText(datos[0]);
        textTotal.setText(datos[1]);
        for(int i = 0; i < prod.size(); i++){
            item(prod, i);
        }
        frame.setContentPane(detalles);
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    void item(ArrayList<Productos> prod, int i){
        JLabel nombre = new JLabel(prod.get(i).getNombre());
        JLabel cantidad = new JLabel(String.valueOf(prod.get(i).getCantidad()));
        JLabel precio = new JLabel(String.valueOf(prod.get(i).getPrecio()));
        JLabel total = new JLabel(String.valueOf(prod.get(i).getTotal()));
        JLabel articulo = new JLabel("Articulo: ");
        JLabel cant = new JLabel("Cantidad: ");
        JLabel prec = new JLabel("Precio: ");
        JLabel tot = new JLabel("Total: ");
        JPanel con = new JPanel();
        con.setMaximumSize(new Dimension(5454655, 25));
        con.setVisible(true);
        
        con.add(articulo);
        con.add(nombre);
        con.add(cant);
        con.add(cantidad);
        con.add(prec);
        con.add(precio);
        con.add(tot);
        con.add(total);
        contenido.add(con);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detalles = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textID = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textCliente = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textTotal = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaRegistros = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        detalles.setLayout(new javax.swing.BoxLayout(detalles, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel9.setMaximumSize(new java.awt.Dimension(318, 50));
        jPanel9.setMinimumSize(new java.awt.Dimension(318, 50));
        jPanel9.setPreferredSize(new java.awt.Dimension(518, 50));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Detalles de Venta");
        jPanel9.add(jLabel1);

        detalles.add(jPanel9);

        jPanel8.setMaximumSize(new java.awt.Dimension(545645656, 60));
        jPanel8.setMinimumSize(new java.awt.Dimension(0, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ID");

        textID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Cliente");

        textCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Total");

        textTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(textCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(textTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(textTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        detalles.add(jPanel8);

        contenido.setMaximumSize(new java.awt.Dimension(564654, 564654));
        contenido.setLayout(new javax.swing.BoxLayout(contenido, javax.swing.BoxLayout.PAGE_AXIS));
        detalles.add(contenido);

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 25));
        jPanel3.setMinimumSize(new java.awt.Dimension(56, 25));
        jPanel3.setPreferredSize(new java.awt.Dimension(630, 25));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jComboBox1.setMaximumRowCount(2);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ventas", "Entradas" }));
        jPanel3.add(jComboBox1);

        add(jPanel3);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        TablaRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaRegistrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaRegistros);

        jPanel1.add(jScrollPane1);

        add(jPanel1);

        jPanel2.setMaximumSize(new java.awt.Dimension(6545621, 40));
        jPanel2.setMinimumSize(new java.awt.Dimension(71, 40));
        jPanel2.setPreferredSize(new java.awt.Dimension(630, 40));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6);

        jButton2.setText("Detalles");
        jPanel2.add(jButton2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5);

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void TablaRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaRegistrosMouseClicked
        if(evt.getClickCount() == 2){
            LlenarFrame();
        }
    }//GEN-LAST:event_TablaRegistrosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setTabla("", "", "");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaRegistros;
    private javax.swing.JPanel contenido;
    private javax.swing.JPanel detalles;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel textCliente;
    private javax.swing.JLabel textID;
    private javax.swing.JLabel textTotal;
    // End of variables declaration//GEN-END:variables
}
