/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.Toolkit;
import javax.swing.JFrame;
import spv.SPV;

/**
 *
 * @author Javier
 */
public class Venta extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public Venta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Productopane = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel8 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();
        Cliente = new javax.swing.JLabel();
        Buscar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();

        Productopane.setLayout(new javax.swing.BoxLayout(Productopane, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel18.setMaximumSize(new java.awt.Dimension(32767, 23));
        jPanel18.setMinimumSize(new java.awt.Dimension(0, 23));
        jPanel18.setPreferredSize(new java.awt.Dimension(637, 23));
        jPanel18.setLayout(new javax.swing.BoxLayout(jPanel18, javax.swing.BoxLayout.LINE_AXIS));

        jPanel11.setMaximumSize(new java.awt.Dimension(73, 32767));
        jPanel11.setMinimumSize(new java.awt.Dimension(73, 0));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel18.add(jPanel11);

        jPanel12.setMaximumSize(new java.awt.Dimension(65465, 14));
        jPanel12.setMinimumSize(new java.awt.Dimension(60, 14));
        jPanel12.setPreferredSize(new java.awt.Dimension(320, 14));
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.LINE_AXIS));

        jLabel10.setText("Codigo");
        jPanel12.add(jLabel10);

        jPanel18.add(jPanel12);

        jPanel13.setMaximumSize(new java.awt.Dimension(4545, 14));
        jPanel13.setPreferredSize(new java.awt.Dimension(318, 14));
        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));

        jLabel11.setText("Nombre");
        jPanel13.add(jLabel11);

        jPanel18.add(jPanel13);

        Productopane.add(jPanel18);

        jPanel19.setMaximumSize(new java.awt.Dimension(32767, 23));
        jPanel19.setMinimumSize(new java.awt.Dimension(0, 23));
        jPanel19.setPreferredSize(new java.awt.Dimension(637, 23));
        jPanel19.setLayout(new javax.swing.BoxLayout(jPanel19, javax.swing.BoxLayout.LINE_AXIS));

        jButton4.setText("Producto");
        jPanel19.add(jButton4);
        jPanel19.add(jTextField7);
        jPanel19.add(jTextField8);

        Productopane.add(jPanel19);

        jPanel20.setLayout(new javax.swing.BoxLayout(jPanel20, javax.swing.BoxLayout.LINE_AXIS));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel20.add(jScrollPane2);

        Productopane.add(jPanel20);

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 100));
        jPanel4.setMinimumSize(new java.awt.Dimension(766, 100));
        jPanel4.setPreferredSize(new java.awt.Dimension(500, 100));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel10.setMaximumSize(new java.awt.Dimension(32767, 25));
        jPanel10.setMinimumSize(new java.awt.Dimension(56, 25));
        jPanel10.setPreferredSize(new java.awt.Dimension(812, 25));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Captura por Cliente", "Captura Continuada" }));
        jPanel10.add(jComboBox1);

        jPanel4.add(jPanel10);

        jPanel8.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel8.setMinimumSize(new java.awt.Dimension(373, 30));
        jPanel8.setPreferredSize(new java.awt.Dimension(820, 30));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cliente Recurrente", "Cliente Ocacional" }));
        jPanel8.add(jComboBox2);

        Cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Cliente.setText("Cliente");
        jPanel8.add(Cliente);

        Buscar.setMaximumSize(new java.awt.Dimension(2147483647, 25));
        Buscar.setMinimumSize(new java.awt.Dimension(6, 25));
        Buscar.setPreferredSize(new java.awt.Dimension(300, 25));
        jPanel8.add(Buscar);

        jButton2.setText("Buscar");
        jPanel8.add(jButton2);

        jPanel4.add(jPanel8);

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel1.setMinimumSize(new java.awt.Dimension(766, 40));
        jPanel1.setPreferredSize(new java.awt.Dimension(766, 40));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(350, 20));
        jLabel1.setMinimumSize(new java.awt.Dimension(250, 20));
        jLabel1.setPreferredSize(new java.awt.Dimension(250, 20));
        jPanel1.add(jLabel1);

        jLabel2.setText("jLabel1");
        jLabel2.setMaximumSize(new java.awt.Dimension(350, 20));
        jLabel2.setMinimumSize(new java.awt.Dimension(150, 20));
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel1.add(jLabel2);

        jPanel4.add(jPanel1);

        add(jPanel4);

        jPanel5.setMaximumSize(new java.awt.Dimension(32767, 1000));
        jPanel5.setMinimumSize(new java.awt.Dimension(0, 90));
        jPanel5.setPreferredSize(new java.awt.Dimension(812, 300));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);

        jPanel5.add(jPanel2);

        add(jPanel5);

        jPanel6.setMaximumSize(new java.awt.Dimension(32767, 100));
        jPanel6.setMinimumSize(new java.awt.Dimension(0, 100));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel7.setMaximumSize(new java.awt.Dimension(32767, 23));
        jPanel7.setMinimumSize(new java.awt.Dimension(100, 23));
        jPanel7.setPreferredSize(new java.awt.Dimension(812, 23));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Codigo");
        jLabel4.setMaximumSize(new java.awt.Dimension(320, 14));
        jLabel4.setMinimumSize(new java.awt.Dimension(320, 14));
        jLabel4.setPreferredSize(new java.awt.Dimension(320, 14));
        jPanel7.add(jLabel4);

        jLabel5.setText("Nombre");
        jLabel5.setMaximumSize(new java.awt.Dimension(244444, 14));
        jLabel5.setMinimumSize(new java.awt.Dimension(50, 14));
        jLabel5.setPreferredSize(new java.awt.Dimension(175, 14));
        jPanel7.add(jLabel5);

        jLabel6.setText("Cantidad");
        jLabel6.setMaximumSize(new java.awt.Dimension(70, 14));
        jLabel6.setMinimumSize(new java.awt.Dimension(70, 14));
        jLabel6.setPreferredSize(new java.awt.Dimension(70, 14));
        jPanel7.add(jLabel6);

        jLabel7.setText("Precio");
        jLabel7.setMaximumSize(new java.awt.Dimension(58, 14));
        jLabel7.setMinimumSize(new java.awt.Dimension(58, 14));
        jLabel7.setPreferredSize(new java.awt.Dimension(58, 14));
        jPanel7.add(jLabel7);

        jLabel8.setText("Descuento");
        jLabel8.setMaximumSize(new java.awt.Dimension(80, 14));
        jLabel8.setMinimumSize(new java.awt.Dimension(80, 14));
        jLabel8.setPreferredSize(new java.awt.Dimension(80, 14));
        jPanel7.add(jLabel8);

        jLabel9.setText("I.V.A");
        jLabel9.setMaximumSize(new java.awt.Dimension(120, 14));
        jLabel9.setMinimumSize(new java.awt.Dimension(120, 14));
        jLabel9.setPreferredSize(new java.awt.Dimension(120, 14));
        jPanel7.add(jLabel9);

        jPanel6.add(jPanel7);

        jPanel3.setMaximumSize(new java.awt.Dimension(214748364, 23));
        jPanel3.setPreferredSize(new java.awt.Dimension(812, 23));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setText("Producto");
        jPanel3.add(jLabel3);

        jButton3.setText("...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        jTextField1.setMaximumSize(new java.awt.Dimension(150, 2147483647));
        jTextField1.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextField1.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel3.add(jTextField1);
        jPanel3.add(jTextField2);

        jTextField3.setMaximumSize(new java.awt.Dimension(65, 2147483647));
        jTextField3.setMinimumSize(new java.awt.Dimension(65, 20));
        jTextField3.setName(""); // NOI18N
        jTextField3.setPreferredSize(new java.awt.Dimension(65, 20));
        jPanel3.add(jTextField3);

        jTextField4.setMaximumSize(new java.awt.Dimension(65, 2147483647));
        jTextField4.setMinimumSize(new java.awt.Dimension(65, 20));
        jTextField4.setPreferredSize(new java.awt.Dimension(65, 20));
        jPanel3.add(jTextField4);

        jTextField5.setMaximumSize(new java.awt.Dimension(65, 2147483647));
        jTextField5.setMinimumSize(new java.awt.Dimension(65, 20));
        jTextField5.setPreferredSize(new java.awt.Dimension(65, 20));
        jPanel3.add(jTextField5);

        jTextField6.setMaximumSize(new java.awt.Dimension(65, 2147483647));
        jTextField6.setMinimumSize(new java.awt.Dimension(65, 20));
        jTextField6.setPreferredSize(new java.awt.Dimension(65, 20));
        jPanel3.add(jTextField6);

        jButton1.setText("Agregar");
        jPanel3.add(jButton1);

        jPanel6.add(jPanel3);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 812, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel9);

        add(jPanel6);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFrame producto = new JFrame();
        producto.setContentPane(Productopane);
        producto.setIconImage(Toolkit.getDefaultToolkit().getImage(SPV.class.getResource("Jumbo.png")));
        producto.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        producto.setSize(600,450);
        producto.setResizable(true);
        producto.setVisible(true);
        producto.setLocationRelativeTo(null);
        producto.setTitle("Busqueda de Producto");
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Buscar;
    private javax.swing.JLabel Cliente;
    private javax.swing.JPanel Productopane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
