/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spv;

import Ventanas.Recepcion;
import Ventanas.Venta;
import java.awt.CardLayout;
import java.awt.Dimension;
import Conexion.Download;
import Ventanas.Registros;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author Javier
 */
public class MFrame extends javax.swing.JFrame implements Runnable {

    Download dw;
    boolean downloading = false;
    
    Dimension ss = Toolkit.getDefaultToolkit ().getScreenSize ();
    
    public MFrame() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(SPV.class.getResource("Jumbo.png")));
        this.setTitle("Sistema Punto de Venta");
        this.setLocationRelativeTo(null);
        this.pack();
        this.setSize(new Dimension(980,600));
        this.setResizable(true);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setVisible(true);
        initComponents();
        init();
    }
    final void init(){
        Thread thread = new Thread(this);
        thread.start();
        Actualizando.setVisible(false);
        progress.setVisible(false);
        porsentaje.setVisible(false);
        conectadoa.setText("Conectado a: "+ReadFiles.GetBD());
        servera.setText("Server: "+ReadFiles.GetServer());
    }

    public void CambiarCarta(String nwCard){
        CardLayout cl = (CardLayout)(jPanel1.getLayout());
        cl.show(jPanel1,nwCard);
    }
    
    public void ActualizarLC(){
        
        String a[] = ReadFiles.readFromWeb("http://shiftsoftmx.com/Productos/Updates/SPV/Update.txt",1);
        String LCVersion[] = a[0].split(":");
        
        if(ReadFiles.GetLCVersion() < Float.parseFloat(LCVersion[1])){
            Actualizando.setVisible(true);
            progress.setVisible(true);
            porsentaje.setVisible(true);
            downloading = true;
            dw = new Download("http://shiftsoftmx.com/Productos/Updates/SPV/SPV.jar");
            ReadFiles.WriteLCVer(LCVersion[1]);
        }else{
            noUpdate.setVisible(true);
            noUpdate.setText("No hay Actualizacion");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        servera = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        conectadoa = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Actualizando = new javax.swing.JLabel();
        progress = new javax.swing.JProgressBar();
        porsentaje = new javax.swing.JLabel();
        noUpdate = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Ventanas = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        VAdicional = new javax.swing.JMenu();
        PV = new javax.swing.JMenuItem();
        Acerca = new javax.swing.JMenu();
        spv = new javax.swing.JMenuItem();
        Shift = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(ss.width / 2 - getWidth() / 2,ss.height / 2 - getHeight() / 2,getWidth(), getHeight());
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(980, 600));
        setPreferredSize(new java.awt.Dimension(980, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(1050, 600));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, "card2");

        jPanel1.add(jPanel2, "Card1");
        jPanel1.add(new Venta(), "Card2");
        jPanel1.add(new Recepcion(), "Card3");
        jPanel1.add(new Registros(), "Card4");

        getContentPane().add(jPanel1);

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel3.setMinimumSize(new java.awt.Dimension(0, 30));
        jPanel3.setPreferredSize(new java.awt.Dimension(661, 30));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel4.setMaximumSize(new java.awt.Dimension(345549, 23));
        jPanel4.setMinimumSize(new java.awt.Dimension(43, 23));
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 23));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        servera.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        servera.setText("Server: ");
        jPanel4.add(servera);

        jPanel3.add(jPanel4);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel6.setMaximumSize(new java.awt.Dimension(345549, 23));
        jPanel6.setMinimumSize(new java.awt.Dimension(72, 23));
        jPanel6.setPreferredSize(new java.awt.Dimension(34, 23));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        conectadoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        conectadoa.setText("Conectado a: ");
        jPanel6.add(conectadoa);

        jPanel3.add(jPanel6);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel5.setMaximumSize(new java.awt.Dimension(330, 30));
        jPanel5.setMinimumSize(new java.awt.Dimension(330, 30));
        jPanel5.setPreferredSize(new java.awt.Dimension(330, 30));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        Actualizando.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Actualizando.setText("Actualizando");
        Actualizando.setMaximumSize(new java.awt.Dimension(79, 20));
        Actualizando.setMinimumSize(new java.awt.Dimension(79, 20));
        Actualizando.setPreferredSize(new java.awt.Dimension(79, 20));
        jPanel5.add(Actualizando);
        jPanel5.add(progress);

        porsentaje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        porsentaje.setMaximumSize(new java.awt.Dimension(40, 14));
        porsentaje.setMinimumSize(new java.awt.Dimension(40, 14));
        porsentaje.setPreferredSize(new java.awt.Dimension(40, 14));
        jPanel5.add(porsentaje);

        noUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        noUpdate.setMaximumSize(new java.awt.Dimension(54654554, 23));
        noUpdate.setMinimumSize(new java.awt.Dimension(0, 23));
        noUpdate.setPreferredSize(new java.awt.Dimension(0, 23));
        jPanel5.add(noUpdate);

        jPanel3.add(jPanel5);

        getContentPane().add(jPanel3);

        Ventanas.setText("Ventanas");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/punt.png"))); // NOI18N
        jMenuItem3.setText("Punto de Venta");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Ventanas.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/caja.png"))); // NOI18N
        jMenuItem4.setText("Recepcion de Mercancia");
        jMenuItem4.setToolTipText("");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Ventanas.add(jMenuItem4);

        jMenuItem1.setText("Registros");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Ventanas.add(jMenuItem1);

        jMenuBar1.add(Ventanas);

        VAdicional.setText("Venta Adicional");

        PV.setText("Punto de Venta");
        PV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PVActionPerformed(evt);
            }
        });
        VAdicional.add(PV);

        jMenuBar1.add(VAdicional);

        Acerca.setText("Acerca de...");

        spv.setText("Programa (SPV)");
        Acerca.add(spv);

        Shift.setText("Shift Soft");
        Acerca.add(Shift);

        jMenuBar1.add(Acerca);

        Salir.setText("Salir");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cross.png"))); // NOI18N
        jMenuItem2.setText("Salir Definitivamente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Salir.add(jMenuItem2);

        jMenuBar1.add(Salir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        CambiarCarta("Card2");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        CambiarCarta("Card3");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void PVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PVActionPerformed
        MFrame m = new MFrame();
        setVisible(true);
    }//GEN-LAST:event_PVActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CambiarCarta("Card4");
    }//GEN-LAST:event_jMenuItem1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Acerca;
    private javax.swing.JLabel Actualizando;
    private javax.swing.JMenuItem PV;
    private javax.swing.JMenu Salir;
    private javax.swing.JMenuItem Shift;
    private javax.swing.JMenu VAdicional;
    private javax.swing.JMenu Ventanas;
    private javax.swing.JLabel conectadoa;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel noUpdate;
    private javax.swing.JLabel porsentaje;
    private javax.swing.JProgressBar progress;
    private javax.swing.JLabel servera;
    private javax.swing.JMenuItem spv;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        ActualizarLC();
        if(downloading){
            while((int)dw.getProgress() != 100){
            progress.setValue((int)dw.getProgress());
            porsentaje.setText((int)dw.getProgress()+"%");
            }
        }
        Actualizando.setText("Completado");
        porsentaje.setText("100%");
        progress.setVisible(false);
    }
}
