/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spv;

import Ventanas.Recepcion;
import Ventanas.Venta;
import java.awt.CardLayout;
import java.awt.Dimension;
import javax.swing.JFrame;

/**
 *
 * @author Javier
 */
public class MFrame extends javax.swing.JFrame {

    /**
     * Creates new form MFrame
     */
    public MFrame() {
        this.setTitle("Sistema Punto de Venta");
        this.setLocationRelativeTo(null);
        this.setSize(new Dimension(800,600));
        this.setResizable(true);
        this.setVisible(true);
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public void CambiarCarta(String nwCard){
        CardLayout cl = (CardLayout)(jPanel1.getLayout());
        cl.show(jPanel1,nwCard);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        Guardar = new javax.swing.JMenuItem();
        Exportar = new javax.swing.JMenuItem();
        Ventanas = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        VAdicional = new javax.swing.JMenu();
        PV = new javax.swing.JMenuItem();
        Crear = new javax.swing.JMenu();
        Tabla = new javax.swing.JMenuItem();
        BD = new javax.swing.JMenuItem();
        Acerca = new javax.swing.JMenu();
        spv = new javax.swing.JMenuItem();
        Shift = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, "card2");

        jPanel1.add(jPanel2, "Card1");
        jPanel1.add(new Venta(), "Card2");
        jPanel1.add(new Recepcion(), "Card3");

        Archivo.setText("Archivo");

        Guardar.setText("Guardar");
        Archivo.add(Guardar);

        Exportar.setText("Exportar");
        Archivo.add(Exportar);

        jMenuBar1.add(Archivo);

        Ventanas.setText("Ventanas");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/punt.png"))); // NOI18N
        jMenuItem3.setText("Punto de Venta");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Ventanas.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/caja.png"))); // NOI18N
        jMenuItem4.setText("Recepcion de Mercancia");
        jMenuItem4.setToolTipText("");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Ventanas.add(jMenuItem4);

        jMenuBar1.add(Ventanas);

        VAdicional.setText("Venta Adicional");

        PV.setText("Punto de Venta");
        PV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PVActionPerformed(evt);
            }
        });
        VAdicional.add(PV);

        jMenuBar1.add(VAdicional);

        Crear.setText("Crear");
        Crear.setActionCommand("");

        Tabla.setText("Tabla");
        Crear.add(Tabla);

        BD.setText("Base de Datos");
        Crear.add(BD);

        jMenuBar1.add(Crear);

        Acerca.setText("Acerca de...");

        spv.setText("Programa (SPV)");
        Acerca.add(spv);

        Shift.setText("Shift Soft");
        Acerca.add(Shift);

        jMenuBar1.add(Acerca);

        Salir.setText("Salir");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cross.png"))); // NOI18N
        jMenuItem2.setText("Salir Definitivamente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Salir.add(jMenuItem2);

        jMenuBar1.add(Salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        CambiarCarta("Card2");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        CambiarCarta("Card3");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void PVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PVActionPerformed
        MFrame m = new MFrame();
        setVisible(true);
    }//GEN-LAST:event_PVActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Acerca;
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenuItem BD;
    private javax.swing.JMenu Crear;
    private javax.swing.JMenuItem Exportar;
    private javax.swing.JMenuItem Guardar;
    private javax.swing.JMenuItem PV;
    private javax.swing.JMenu Salir;
    private javax.swing.JMenuItem Shift;
    private javax.swing.JMenuItem Tabla;
    private javax.swing.JMenu VAdicional;
    private javax.swing.JMenu Ventanas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem spv;
    // End of variables declaration//GEN-END:variables
}
